import { DEFAULT_OG } from "./article-bodies";

function mpSeo(title: string, description: string, keywords: string) {
  return {
    seo_title: `${title} | Marketplace Saúde & Bem`,
    seo_description: description,
    seo_keywords: keywords,
    og_image_url: DEFAULT_OG,
    image_url: DEFAULT_OG,
  };
}

/** 10 produtos — conteúdo real + SEO (Fase 5.1) */
export const CONTENT_ENGINE_MARKETPLACE_PRODUCTS = [
  {
    id: "e5000005-0005-4005-8005-000000000001",
    slug: "guia-hidratacao-digital",
    title: "Guia da Hidratação",
    description: "E-book gratuito com meta diária, sinais de desidratação e rotina prática.",
    ...mpSeo("Guia da Hidratação", "Baixe o guia gratuito de hidratação — meta personalizada e rotina diária.", "hidratação, ebook, gratuito"),
    category: "hidratacao",
    category_label: "Hidratação",
    product_type: "ebook",
    fulfillment: "digital",
    is_premium: false,
    library_slug: "guia-hidratacao",
    health_tags: ["water", "metabolism"],
    featured: true,
    editor_choice: false,
  },
  {
    id: "e5000005-0005-4005-8005-000000000002",
    slug: "manual-longevidade-digital",
    title: "Manual da Longevidade",
    description: "E-book premium com estratégias baseadas em evidências para envelhecimento ativo.",
    ...mpSeo("Manual da Longevidade", "Manual premium de longevidade — nutrição, movimento e biomarcadores.", "longevidade, premium, ebook"),
    category: "longevidade",
    category_label: "Longevidade",
    product_type: "ebook",
    fulfillment: "digital",
    is_premium: true,
    library_slug: "manual-longevidade",
    health_tags: ["habits", "cardiometabolic"],
    featured: false,
    editor_choice: true,
  },
  {
    id: "e5000005-0005-4005-8005-000000000003",
    slug: "sono-reparador-digital",
    title: "E-book Sono Reparador",
    description: "Guia digital gratuito de higiene do sono e rotinas noturnas.",
    ...mpSeo("E-book Sono Reparador", "Guia gratuito de higiene do sono e rotinas noturnas reparadoras.", "sono, ebook, gratuito"),
    category: "sono",
    category_label: "Sono",
    product_type: "ebook",
    fulfillment: "digital",
    is_premium: false,
    library_slug: "sono-reparador-ebook",
    health_tags: ["habits"],
    featured: false,
    editor_choice: false,
  },
  {
    id: "e5000005-0005-4005-8005-000000000004",
    slug: "kit-emagrecimento-proprio",
    title: "Kit Emagrecimento Saúde & Bem",
    description: "Produto próprio Saúde & Bem: e-book + planilha de acompanhamento + checklist semanal.",
    ...mpSeo("Kit Emagrecimento", "Kit próprio com e-book, planilha e checklist para emagrecimento sustentável.", "emagrecimento, kit, produto próprio"),
    category: "emagrecimento",
    category_label: "Emagrecimento",
    product_type: "kit",
    fulfillment: "own",
    is_premium: false,
    current_price: 47.0,
    old_price: 79.0,
    library_slug: "guia-emagrecimento-metabolico",
    health_tags: ["bmi", "protein", "metabolism"],
    featured: true,
    editor_choice: false,
  },
  {
    id: "e5000005-0005-4005-8005-000000000005",
    slug: "coracao-saudavel-proprio",
    title: "Programa Coração Saudável",
    description: "Produto próprio premium: e-book, protocolo e materiais de acompanhamento cardiovascular.",
    ...mpSeo("Programa Coração Saudável", "Programa próprio premium de prevenção cardiovascular.", "coração, cardiovascular, premium"),
    category: "saude-cardiovascular",
    category_label: "Saúde Cardiovascular",
    product_type: "ebook",
    fulfillment: "own",
    is_premium: true,
    current_price: 67.0,
    library_slug: "coracao-saudavel",
    health_tags: ["cardiometabolic", "habits"],
    featured: false,
    editor_choice: true,
  },
  {
    id: "e5000005-0005-4005-8005-000000000006",
    slug: "omega-3-cardiovascular",
    title: "Ômega-3 Ultra Pure",
    description: "Suplemento com EPA/DHA de alta pureza — apoio cardiometabólico (afiliado).",
    ...mpSeo("Ômega-3 Ultra Pure", "Ômega-3 de alta pureza para apoio cardiometabólico — oferta afiliada.", "ômega-3, suplemento, afiliado"),
    category: "saude-cardiovascular",
    category_label: "Saúde Cardiovascular",
    product_type: "suplemento",
    fulfillment: "affiliate",
    is_premium: false,
    current_price: 89.9,
    affiliate_slug: "omega-3-cardiovascular",
    health_tags: ["cardiometabolic"],
    featured: false,
    editor_choice: false,
  },
  {
    id: "e5000005-0005-4005-8005-000000000007",
    slug: "monitor-sono-inteligente",
    title: "Monitor de Sono Inteligente",
    description: "Dispositivo wearable para acompanhar ciclos de sono e recuperação (afiliado).",
    ...mpSeo("Monitor de Sono", "Wearable para monitorar sono e recuperação — oferta afiliada.", "sono, wearable, afiliado"),
    category: "sono",
    category_label: "Sono",
    product_type: "dispositivo",
    fulfillment: "affiliate",
    is_premium: false,
    current_price: 349.0,
    installments: "10x sem juros",
    affiliate_slug: "monitor-sono-inteligente",
    health_tags: ["habits"],
    featured: false,
    editor_choice: false,
  },
  {
    id: "e5000005-0005-4005-8005-000000000008",
    slug: "curso-metabolismo-ativo",
    title: "Curso Metabolismo Ativo",
    description: "Curso online sobre nutrição, treino e hábitos para composição corporal (afiliado).",
    ...mpSeo("Curso Metabolismo Ativo", "Curso online de nutrição e treino para composição corporal.", "curso, emagrecimento, afiliado"),
    category: "emagrecimento",
    category_label: "Emagrecimento",
    product_type: "curso",
    fulfillment: "affiliate",
    is_premium: false,
    current_price: 197.0,
    affiliate_slug: "curso-metabolismo-ativo",
    health_tags: ["bmi", "metabolism"],
    featured: true,
    editor_choice: false,
  },
  {
    id: "e5000005-0005-4005-8005-000000000009",
    slug: "checklist-preventiva-digital",
    title: "Checklist Saúde Preventiva",
    description: "Material digital gratuito para acompanhamento preventivo anual.",
    ...mpSeo("Checklist Saúde Preventiva", "Checklist digital gratuito de prevenção e exames anuais.", "prevenção, checklist, gratuito"),
    category: "longevidade",
    category_label: "Longevidade",
    product_type: "ebook",
    fulfillment: "digital",
    is_premium: false,
    library_slug: "checklist-saude-preventiva",
    health_tags: ["habits", "cardiometabolic"],
    featured: false,
    editor_choice: false,
  },
  {
    id: "e5000005-0005-4005-8005-000000000010",
    slug: "clube-saude-bem-premium",
    title: "Clube Saúde & Bem Premium",
    description: "Assinatura Clube Saúde & Bem Premium — biblioteca, protocolos e área de membros.",
    ...mpSeo("Clube Saúde & Bem Premium", "Assine o Clube Premium: biblioteca exclusiva, protocolos e área de membros.", "clube, assinatura, premium"),
    category: "longevidade",
    category_label: "Assinatura",
    product_type: "servico",
    fulfillment: "subscription",
    is_premium: true,
    current_price: 29.9,
    health_tags: ["habits", "cardiometabolic", "metabolism"],
    featured: false,
    editor_choice: false,
  },
] as const;
