import type { MarketplaceItem } from "./marketplace.types";

/**
 * Catálogo mock — Fase 4.9.
 * Itens digitais referenciam a biblioteca inteligente; afiliados são enriquecidos via Supabase.
 */
export const MARKETPLACE_CATALOG: MarketplaceItem[] = [
  {
    id: "mp-digital-001",
    slug: "guia-hidratacao-digital",
    title: "Guia da Hidratação",
    description: "E-book gratuito com meta diária, sinais de desidratação e rotina prática.",
    category: "nutricao",
    categoryLabel: "Nutrição",
    productType: "ebook",
    fulfillment: "digital",
    isPremium: false,
    librarySlug: "guia-hidratacao",
    healthTags: ["water", "metabolism"],
    featured: true,
  },
  {
    id: "mp-digital-002",
    slug: "manual-longevidade-digital",
    title: "Manual da Longevidade",
    description: "E-book premium com estratégias baseadas em evidências para envelhecimento ativo.",
    category: "longevidade",
    categoryLabel: "Longevidade",
    productType: "ebook",
    fulfillment: "digital",
    isPremium: true,
    librarySlug: "manual-longevidade",
    healthTags: ["habits", "cardiometabolic"],
    editorChoice: true,
  },
  {
    id: "mp-digital-003",
    slug: "protocolo-energia-digital",
    title: "Protocolo Energia Diária",
    description: "Plano digital de 21 dias para vitalidade e rotina matinal estruturada.",
    category: "energia",
    categoryLabel: "Energia",
    productType: "protocolo",
    fulfillment: "digital",
    isPremium: false,
    librarySlug: "protocolo-energia-diaria",
    healthTags: ["metabolism", "habits"],
  },
  {
    id: "mp-digital-004",
    slug: "plano-metabolico-digital",
    title: "Plano Saúde Metabólica",
    description: "Programa digital premium de 28 dias para equilíbrio glicêmico e composição corporal.",
    category: "nutricao",
    categoryLabel: "Metabolismo",
    productType: "protocolo",
    fulfillment: "digital",
    isPremium: true,
    librarySlug: "plano-saude-metabolica",
    healthTags: ["bmi", "protein", "metabolism"],
  },
  {
    id: "mp-affiliate-001",
    slug: "omega-3-cardiovascular",
    title: "Ômega-3 Ultra Pure",
    description: "Suplemento com EPA/DHA de alta pureza — apoio cardiometabólico.",
    category: "nutricao",
    categoryLabel: "Nutrição",
    productType: "suplemento",
    fulfillment: "affiliate",
    isPremium: false,
    currentPrice: 89.9,
    healthTags: ["cardiometabolic", "protein"],
  },
  {
    id: "mp-affiliate-002",
    slug: "monitor-sono-inteligente",
    title: "Monitor de Sono Inteligente",
    description: "Dispositivo wearable para acompanhar ciclos de sono e recuperação.",
    category: "sono",
    categoryLabel: "Sono",
    productType: "dispositivo",
    fulfillment: "affiliate",
    isPremium: false,
    currentPrice: 349.0,
    installments: "10x sem juros",
    healthTags: ["habits"],
  },
  {
    id: "mp-affiliate-003",
    slug: "curso-metabolismo-ativo",
    title: "Curso Metabolismo Ativo",
    description: "Curso online sobre nutrição, treino e hábitos para composição corporal.",
    category: "energia",
    categoryLabel: "Energia",
    productType: "curso",
    fulfillment: "affiliate",
    isPremium: false,
    currentPrice: 197.0,
    healthTags: ["bmi", "metabolism", "protein"],
    featured: true,
  },
  {
    id: "mp-subscription-001",
    slug: "clube-saude-bem-premium",
    title: "Clube Saúde & Bem Premium",
    description: "Assinatura com biblioteca premium, protocolos avançados e área de membros.",
    category: "longevidade",
    categoryLabel: "Assinatura",
    productType: "servico",
    fulfillment: "subscription",
    isPremium: true,
    currentPrice: 29.9,
    healthTags: ["habits", "cardiometabolic", "metabolism"],
  },
];

export function getCatalogItemBySlug(slug: string): MarketplaceItem | undefined {
  return MARKETPLACE_CATALOG.find((item) => item.slug === slug);
}
