-- =============================================================================
-- Saúde & Bem — Seed de conteúdo (Fase 2.5)
-- Gerado por scripts/generate-content-seed.mjs
-- Execute após 002_content_and_favorites.sql
-- =============================================================================

-- Limpa seed anterior (ids determinísticos)
delete from public.favorites where content_id in (
  select id from public.articles where id::text like 'a1000001-%'
  union select id from public.protocols where id::text like 'b2000002-%'
  union select id from public.ebooks where id::text like 'c3000003-%'
);
delete from public.articles where id::text like 'a1000001-%';
delete from public.protocols where id::text like 'b2000002-%';
delete from public.ebooks where id::text like 'c3000003-%';

-- Articles
insert into public.articles (id, slug, title, excerpt, content, category, category_label, author, author_role, read_time, published_at, featured, status) values ('a1000001-0001-4001-8001-000000000001', 'pilares-longevidade-2026', 'Os 5 pilares da longevidade que a ciência confirma', 'Descubra os hábitos com maior evidência científica para viver mais e melhor — sem modismos ou promessas vazias.', '["A longevidade de qualidade nasce de hábitos consistentes com respaldo científico. Em 2026, cinco pilares se destacam na literatura.","Sono reparador, nutrição anti-inflamatória, movimento regular, gestão do estresse e conexões sociais formam a base de uma vida longa e plena."]'::jsonb, 'longevidade', 'Longevidade', 'Dra. Marina Alves', 'Medicina Preventiva', '8 min', '28 Mai 2026', true, 'published');
insert into public.articles (id, slug, title, excerpt, content, category, category_label, author, author_role, read_time, published_at, featured, status) values ('a1000001-0001-4001-8001-000000000002', 'energia-sem-cafeina', 'Energia sustentável sem depender de cafeína', 'Estratégias circadianas e nutricionais para manter vitalidade consistente ao longo do dia.', '["Energia sustentável vem de ritmo circadiano alinhado, hidratação, proteína no café da manhã e exposição solar matinal.","Cafeína após 14h pode comprometer sono e criar ciclo de dependência energética que mascarar fadiga crônica."]'::jsonb, 'energia', 'Energia', 'Dra. Marina Alves', 'Medicina Preventiva', '6 min', '22 Mai 2026', false, 'published');
insert into public.articles (id, slug, title, excerpt, content, category, category_label, author, author_role, read_time, published_at, featured, status) values ('a1000001-0001-4001-8001-000000000003', 'sono-imunidade-metabolismo', 'Como o sono impacta imunidade e metabolismo', 'Entenda a conexão entre descanso, hormônios, glicemia e saúde metabólica.', '["Durante o sono profundo, o corpo consolida memória imunológica e regula hormônios metabólicos.","Privação crônica eleva cortisol, piora sensibilidade à insulina e compromete células de defesa."]'::jsonb, 'sono', 'Sono', 'Dr. Rafael Costa', 'Neurociência do Sono', '7 min', '18 Mai 2026', false, 'published');
insert into public.articles (id, slug, title, excerpt, content, category, category_label, author, author_role, read_time, published_at, featured, status) values ('a1000001-0001-4001-8001-000000000004', 'microbiota-saude-integral', 'Microbiota intestinal: a base da saúde integral', 'Como o intestino influencia imunidade, humor, energia e envelhecimento saudável.', '["O eixo intestino-cérebro conecta microbiota, sistema imune e saúde mental de formas surpreendentes.","Alimentos prebióticos, fibras diversas e redução de ultraprocessados são os pilares para microbiota saudável."]'::jsonb, 'saude-intestinal', 'Saúde Intestinal', 'Nutr. Camila Ferreira', 'Nutrição Funcional', '9 min', '14 Mai 2026', false, 'published');
insert into public.articles (id, slug, title, excerpt, content, category, category_label, author, author_role, read_time, published_at, featured, status) values ('a1000001-0001-4001-8001-000000000005', 'alimentacao-anti-inflamatoria', 'Guia prático de alimentação anti-inflamatória', 'Alimentos, combinações e timing para reduzir inflamação crônica de baixo grau.', '["Inflamação crônica silenciosa acelera envelhecimento e impacta energia, peso e humor.","Priorize vegetais coloridos, ômega-3, polifenóis e reduza açúcares refinados e ultraprocessados."]'::jsonb, 'alimentacao', 'Alimentação', 'Nutr. Camila Ferreira', 'Nutrição Funcional', '10 min', '10 Mai 2026', false, 'published');
insert into public.articles (id, slug, title, excerpt, content, category, category_label, author, author_role, read_time, published_at, featured, status) values ('a1000001-0001-4001-8001-000000000006', 'estresse-saude-mental-longevidade', 'Estresse crônico e saúde mental na longevidade', 'Como o cortisol elevado acelera envelhecimento e o que fazer para reverter o ciclo.', '["Estresse crônico eleva cortisol, aumenta inflamação e compromete sono, imunidade e cognição.","Respiração diafragmática, natureza, movimento moderado e limites digitais são intervenções com evidência."]'::jsonb, 'saude-mental', 'Saúde Mental', 'Dra. Marina Alves', 'Medicina Preventiva', '7 min', '5 Mai 2026', false, 'published');
insert into public.articles (id, slug, title, excerpt, content, category, category_label, author, author_role, read_time, published_at, featured, status) values ('a1000001-0001-4001-8001-000000000007', 'biomarcadores-longevidade', 'Biomarcadores de longevidade que você pode acompanhar', 'HbA1c, PCR-us e triglicerídeos — o que pedir e como interpretar com seu médico.', '["Biomarcadores acessíveis oferecem snapshot valioso da saúde metabólica e inflamatória.","Acompanhe tendências ao longo do tempo, não valores isolados, sempre com orientação profissional."]'::jsonb, 'longevidade', 'Longevidade', 'Dr. Rafael Costa', 'Neurociência do Sono', '11 min', '1 Mai 2026', false, 'published');
insert into public.articles (id, slug, title, excerpt, content, category, category_label, author, author_role, read_time, published_at, featured, status) values ('a1000001-0001-4001-8001-000000000008', 'rotina-matinal-energia', 'A rotina matinal ideal para mais energia', '5 hábitos matinais com respaldo científico para começar o dia com clareza e vigor.', '["Exposição solar nos primeiros 30 minutos, hidratação, movimento leve e proteína no café da manhã são os pilares.","Evite celular e cafeína imediata — dê ao corpo tempo para ativar o ritmo circadiano naturalmente."]'::jsonb, 'energia', 'Energia', 'Prof. André Lima', 'Fisiologia do Exercício', '5 min', '26 Abr 2026', false, 'published');

-- Protocols
insert into public.protocols (id, slug, title, description, objective, long_description, category, category_label, duration, level, benefits, steps, is_premium, featured, tag, participants, status) values ('b2000002-0002-4002-8002-000000000001', 'energia-diaria', 'Energia Diária', 'Rotina matinal e hábitos diários para vitalidade consistente, sem depender de estimulantes artificiais.', 'Manter energia estável e foco ao longo de todo o dia.', 'Protocolo de 14 dias que reorganiza seu ritmo circadiano, alimentação matinal e micro-hábitos para energia sustentável baseada em ciência.', 'energia', 'Energia', '14 dias', 'Iniciante', '["Foco prolongado","Menos fadiga vespertina","Sono mais reparador"]'::jsonb, '[{"title":"Dias 1–5","description":"Exposição solar matinal e hidratação estratégica."},{"title":"Dias 6–10","description":"Alimentação energizante e movimento leve."},{"title":"Dias 11–14","description":"Rotina consolidada personalizada."}]'::jsonb, false, true, 'Mais popular', 3240, 'published');
insert into public.protocols (id, slug, title, description, objective, long_description, category, category_label, duration, level, benefits, steps, is_premium, featured, tag, participants, status) values ('b2000002-0002-4002-8002-000000000002', 'sono-reparador', 'Sono Reparador', 'Resete seu ritmo circadiano com higiene do sono baseada em evidências científicas.', 'Dormir mais rápido, profundamente e acordar com disposição.', 'Em 7 dias, você implementará rotinas noturnas, otimização do ambiente e estratégias comportamentais para noites restauradoras.', 'sono', 'Sono', '7 dias', 'Iniciante', '["Latência reduzida","Mais energia matinal","Humor equilibrado"]'::jsonb, '[{"title":"Dia 1–2","description":"Mapeamento do ritmo e horários fixos."},{"title":"Dia 3–4","description":"Ambiente e redução de luz azul."},{"title":"Dia 5–7","description":"Rotina noturna consolidada."}]'::jsonb, false, false, null, 4120, 'published');
insert into public.protocols (id, slug, title, description, objective, long_description, category, category_label, duration, level, benefits, steps, is_premium, featured, tag, participants, status) values ('b2000002-0002-4002-8002-000000000003', 'saude-intestinal', 'Saúde Intestinal', 'Restaure o equilíbrio da microbiota com alimentação funcional e hábitos de lifestyle.', 'Melhorar digestão, absorção de nutrientes e bem-estar intestinal.', 'Protocolo de 21 dias focado em fibras prebióticas, probióticos naturais, redução de inflamação intestinal e reconexão intestino-cérebro.', 'intestinal', 'Saúde Intestinal', '21 dias', 'Intermediário', '["Digestão otimizada","Menos inchaço","Imunidade fortalecida"]'::jsonb, '[{"title":"Semana 1","description":"Eliminação de provocadores intestinais."},{"title":"Semana 2","description":"Introdução de alimentos funcionais."},{"title":"Semana 3","description":"Consolidação e personalização."}]'::jsonb, false, false, null, 2890, 'published');
insert into public.protocols (id, slug, title, description, objective, long_description, category, category_label, duration, level, benefits, steps, is_premium, featured, tag, participants, status) values ('b2000002-0002-4002-8002-000000000004', 'detox-natural', 'Detox Natural', 'Desintoxicação gentil e sustentável — sem dietas restritivas ou promessas milagrosas.', 'Apoiar funções naturais de detoxificação do fígado e eliminação de toxinas.', 'Plano de 10 dias com alimentos detoxificantes, hidratação, movimento e sono para apoiar os processos naturais do corpo.', 'detox', 'Detox', '10 dias', 'Iniciante', '["Mais leveza","Pele radiante","Clareza mental"]'::jsonb, '[{"title":"Dias 1–3","description":"Hidratação e alimentos crucíferos."},{"title":"Dias 4–7","description":"Suporte hepático e eliminação."},{"title":"Dias 8–10","description":"Reintrodução consciente."}]'::jsonb, false, false, null, 1950, 'published');
insert into public.protocols (id, slug, title, description, objective, long_description, category, category_label, duration, level, benefits, steps, is_premium, featured, tag, participants, status) values ('b2000002-0002-4002-8002-000000000005', 'longevidade-saudavel', 'Longevidade Saudável', 'Os pilares comprovados da ciência para envelhecer com qualidade, vitalidade e independência.', 'Implementar hábitos de longevidade baseados em evidências científicas.', 'Protocolo integrado de 90 dias cobrindo nutrição, movimento, sono, gestão do estresse e biomarcadores de envelhecimento saudável.', 'longevidade', 'Longevidade', '90 dias', 'Avançado', '["Marcadores otimizados","Mais energia","Resiliência biológica"]'::jsonb, '[{"title":"Fase 1","description":"Baseline e avaliação de biomarcadores."},{"title":"Fase 2","description":"Implementação dos 5 pilares."},{"title":"Fase 3","description":"Otimização e manutenção."}]'::jsonb, true, false, 'Premium', 870, 'published');
insert into public.protocols (id, slug, title, description, objective, long_description, category, category_label, duration, level, benefits, steps, is_premium, featured, tag, participants, status) values ('b2000002-0002-4002-8002-000000000006', 'menopausa-saudavel', 'Menopausa Saudável', 'Acompanhamento integrado para equilíbrio hormonal, energia e bem-estar na maturidade feminina.', 'Navegar a menopausa com vitalidade, clareza e qualidade de vida.', 'Protocolo de 30 dias com foco em nutrição hormonal, movimento adaptado, gestão de sintomas e saúde óssea e cardiovascular.', 'menopausa', 'Menopausa', '30 dias', 'Intermediário', '["Equilíbrio hormonal","Ossos fortes","Energia estável"]'::jsonb, '[{"title":"Semana 1","description":"Mapeamento de sintomas e alimentação base."},{"title":"Semana 2","description":"Movimento e suplementação estratégica."},{"title":"Semanas 3–4","description":"Consolidação e acompanhamento."}]'::jsonb, true, false, null, 640, 'published');

-- Ebooks
insert into public.ebooks (id, slug, title, description, long_description, category, category_label, icon, format, pages, highlights, is_premium, downloads, featured, status) values ('c3000003-0003-4003-8003-000000000001', 'guia-detox-inteligente', 'Guia Detox Inteligente', 'Desintoxicação gentil e sustentável — alimentos, hábitos e protocolos para apoiar o fígado naturalmente.', 'Guia completo de 24 páginas com plano de 10 dias, lista de alimentos detoxificantes e receitas práticas.', 'Detox', 'Detox', 'leaf', 'PDF', 24, '["Plano de 10 dias","Alimentos detox","Receitas práticas"]'::jsonb, false, 4820, true, 'published');
insert into public.ebooks (id, slug, title, description, long_description, category, category_label, icon, format, pages, highlights, is_premium, downloads, featured, status) values ('c3000003-0003-4003-8003-000000000002', 'guia-energia-natural', 'Guia Energia Natural', 'Estratégias circadianas e nutricionais para vitalidade consistente sem depender de cafeína.', 'Manual de 20 páginas com rotina matinal, alimentos energizantes e protocolos de movimento leve.', 'Energia', 'Energia', 'bolt', 'PDF', 20, '["Rotina matinal","Alimentos-chave","Protocolo de 14 dias"]'::jsonb, false, 3650, false, 'published');
insert into public.ebooks (id, slug, title, description, long_description, category, category_label, icon, format, pages, highlights, is_premium, downloads, featured, status) values ('c3000003-0003-4003-8003-000000000003', 'guia-sono-saudavel', 'Guia Sono Saudável', 'Protocolos práticos para higiene do sono, ambiente ideal e rotinas noturnas reparadoras.', 'Guia de 18 páginas com checklist de ambiente, suplementação baseada em evidências e plano de 7 dias.', 'Sono', 'Sono', 'moon', 'PDF', 18, '["Checklist do quarto","Rotina noturna","Plano de 7 dias"]'::jsonb, false, 3910, false, 'published');
insert into public.ebooks (id, slug, title, description, long_description, category, category_label, icon, format, pages, highlights, is_premium, downloads, featured, status) values ('c3000003-0003-4003-8003-000000000004', 'guia-habitos-saudaveis', 'Guia Hábitos Saudáveis', 'Como construir e manter hábitos duradouros de saúde com base em ciência comportamental.', 'Guia de 16 páginas sobre formação de hábitos, stacking, triggers e estratégias de consistência.', 'Hábitos', 'Hábitos', 'checklist', 'PDF', 16, '["Ciência comportamental","Habit stacking","Plano semanal"]'::jsonb, false, 2780, false, 'published');
insert into public.ebooks (id, slug, title, description, long_description, category, category_label, icon, format, pages, highlights, is_premium, downloads, featured, status) values ('c3000003-0003-4003-8003-000000000005', 'guia-saude-intestinal', 'Guia Saúde Intestinal', 'Microbiota, alimentos prebióticos e protocolos para restaurar o equilíbrio digestivo.', 'Manual de 22 páginas sobre eixo intestino-cérebro, alimentos funcionais e plano de 21 dias.', 'Intestinal', 'Saúde Intestinal', 'vitality', 'PDF', 22, '["Microbiota","Alimentos prebióticos","Plano de 21 dias"]'::jsonb, false, 3240, false, 'published');

select 'articles' as table_name, count(*) as row_count from public.articles
union all select 'protocols', count(*) from public.protocols
union all select 'ebooks', count(*) from public.ebooks;
