-- =============================================================================
-- Saúde & Bem — Seed Content Engine (Fase 5.0 / 5.1)
-- Gerado por scripts/generate-content-seed.mjs
-- Execute após 024_content_engine.sql e 026_seo_content_engine.sql
-- =============================================================================

delete from public.marketplace_products where id::text like 'e5000005-%';
delete from public.library_items where id::text like 'd4000004-%';

-- library_items (6 e-books)
insert into public.library_items (id, slug, title, description, long_description, category, category_label, item_type, tier, is_premium, image_url, estimated_read_time, featured, assets, seo_title, seo_description, seo_keywords, og_image_url, status) values ('d4000004-0004-4004-8004-000000000001', 'guia-hidratacao', 'Guia da Hidratação', 'Meta diária personalizada, sinais de desidratação e rotina prática para manter a hidratação.', 'Meta diária personalizada, sinais de desidratação e rotina prática para manter a hidratação.', 'hidratacao', 'Hidratação', 'ebook', 'free', false, '/logo-saude-bem.png', '8 min de leitura', true, '{"storagePath":"library/ebooks/guia-hidratacao.pdf"}'::jsonb, 'Guia da Hidratação | Biblioteca Saúde & Bem', 'Meta diária personalizada, sinais de desidratação e rotina prática para manter a hidratação.', 'hidratacao', '/logo-saude-bem.png', 'published');
insert into public.library_items (id, slug, title, description, long_description, category, category_label, item_type, tier, is_premium, image_url, estimated_read_time, featured, assets, seo_title, seo_description, seo_keywords, og_image_url, status) values ('d4000004-0004-4004-8004-000000000002', 'checklist-saude-preventiva', 'Checklist Saúde Preventiva', 'Lista objetiva de exames, hábitos e alertas para acompanhamento preventivo anual.', 'Lista objetiva de exames, hábitos e alertas para acompanhamento preventivo anual.', 'prevencao', 'Prevenção', 'ebook', 'free', false, '/logo-saude-bem.png', '5 min de leitura', false, '{"storagePath":"library/ebooks/checklist-saude-preventiva.pdf"}'::jsonb, 'Checklist Saúde Preventiva | Biblioteca Saúde & Bem', 'Lista objetiva de exames, hábitos e alertas para acompanhamento preventivo anual.', 'prevencao', '/logo-saude-bem.png', 'published');
insert into public.library_items (id, slug, title, description, long_description, category, category_label, item_type, tier, is_premium, image_url, estimated_read_time, featured, assets, seo_title, seo_description, seo_keywords, og_image_url, status) values ('d4000004-0004-4004-8004-000000000003', 'sono-reparador-ebook', 'E-book Sono Reparador', 'Guia completo de higiene do sono, ambiente ideal e rotinas noturnas.', 'Guia completo de higiene do sono, ambiente ideal e rotinas noturnas.', 'sono', 'Sono', 'ebook', 'free', false, '/logo-saude-bem.png', '12 min de leitura', false, '{"storagePath":"library/ebooks/sono-reparador.pdf"}'::jsonb, 'E-book Sono Reparador | Biblioteca Saúde & Bem', 'Guia completo de higiene do sono, ambiente ideal e rotinas noturnas.', 'sono', '/logo-saude-bem.png', 'published');
insert into public.library_items (id, slug, title, description, long_description, category, category_label, item_type, tier, is_premium, image_url, estimated_read_time, featured, assets, seo_title, seo_description, seo_keywords, og_image_url, status) values ('d4000004-0004-4004-8004-000000000004', 'manual-longevidade', 'Manual da Longevidade', 'Estratégias baseadas em evidências para envelhecimento ativo — nutrição, movimento e biomarcadores.', 'Estratégias baseadas em evidências para envelhecimento ativo — nutrição, movimento e biomarcadores.', 'longevidade', 'Longevidade', 'ebook', 'premium', true, '/logo-saude-bem.png', '45 min de leitura', false, '{"storagePath":"library/ebooks/manual-longevidade.pdf"}'::jsonb, 'Manual da Longevidade | Biblioteca Saúde & Bem', 'Estratégias baseadas em evidências para envelhecimento ativo — nutrição, movimento e biomarcadores.', 'longevidade', '/logo-saude-bem.png', 'published');
insert into public.library_items (id, slug, title, description, long_description, category, category_label, item_type, tier, is_premium, image_url, estimated_read_time, featured, assets, seo_title, seo_description, seo_keywords, og_image_url, status) values ('d4000004-0004-4004-8004-000000000005', 'guia-emagrecimento-metabolico', 'Guia Emagrecimento Metabólico', 'Plano alimentar e hábitos para perda de gordura sustentável com foco em saúde metabólica.', 'Plano alimentar e hábitos para perda de gordura sustentável com foco em saúde metabólica.', 'emagrecimento', 'Emagrecimento', 'ebook', 'premium', true, '/logo-saude-bem.png', '35 min de leitura', false, '{"storagePath":"library/ebooks/emagrecimento-metabolico.pdf"}'::jsonb, 'Guia Emagrecimento Metabólico | Biblioteca Saúde & Bem', 'Plano alimentar e hábitos para perda de gordura sustentável com foco em saúde metabólica.', 'emagrecimento', '/logo-saude-bem.png', 'published');
insert into public.library_items (id, slug, title, description, long_description, category, category_label, item_type, tier, is_premium, image_url, estimated_read_time, featured, assets, seo_title, seo_description, seo_keywords, og_image_url, status) values ('d4000004-0004-4004-8004-000000000006', 'coracao-saudavel', 'Coração Saudável', 'E-book premium sobre prevenção cardiovascular, alimentação e monitoramento em casa.', 'E-book premium sobre prevenção cardiovascular, alimentação e monitoramento em casa.', 'saude-cardiovascular', 'Saúde Cardiovascular', 'ebook', 'premium', true, '/logo-saude-bem.png', '40 min de leitura', false, '{"storagePath":"library/ebooks/coracao-saudavel.pdf"}'::jsonb, 'Coração Saudável | Biblioteca Saúde & Bem', 'E-book premium sobre prevenção cardiovascular, alimentação e monitoramento em casa.', 'saude-cardiovascular', '/logo-saude-bem.png', 'published');

-- marketplace_products (10)
insert into public.marketplace_products (id, slug, title, description, category, category_label, product_type, fulfillment, is_premium, image_url, current_price, old_price, installments, featured, editor_choice, library_slug, affiliate_slug, health_tags, seo_title, seo_description, seo_keywords, og_image_url, status) values ('e5000005-0005-4005-8005-000000000001', 'guia-hidratacao-digital', 'Guia da Hidratação', 'E-book gratuito com meta diária, sinais de desidratação e rotina prática.', 'hidratacao', 'Hidratação', 'ebook', 'digital', false, '/logo-saude-bem.png', null, null, null, true, false, 'guia-hidratacao', null, array['water', 'metabolism']::text[], 'Guia da Hidratação | Marketplace Saúde & Bem', 'E-book gratuito com meta diária, sinais de desidratação e rotina prática.', 'hidratacao', '/logo-saude-bem.png', 'published');
insert into public.marketplace_products (id, slug, title, description, category, category_label, product_type, fulfillment, is_premium, image_url, current_price, old_price, installments, featured, editor_choice, library_slug, affiliate_slug, health_tags, seo_title, seo_description, seo_keywords, og_image_url, status) values ('e5000005-0005-4005-8005-000000000002', 'manual-longevidade-digital', 'Manual da Longevidade', 'E-book premium com estratégias baseadas em evidências para envelhecimento ativo.', 'longevidade', 'Longevidade', 'ebook', 'digital', true, '/logo-saude-bem.png', null, null, null, false, true, 'manual-longevidade', null, array['habits', 'cardiometabolic']::text[], 'Manual da Longevidade | Marketplace Saúde & Bem', 'E-book premium com estratégias baseadas em evidências para envelhecimento ativo.', 'longevidade', '/logo-saude-bem.png', 'published');
insert into public.marketplace_products (id, slug, title, description, category, category_label, product_type, fulfillment, is_premium, image_url, current_price, old_price, installments, featured, editor_choice, library_slug, affiliate_slug, health_tags, seo_title, seo_description, seo_keywords, og_image_url, status) values ('e5000005-0005-4005-8005-000000000003', 'sono-reparador-digital', 'E-book Sono Reparador', 'Guia digital gratuito de higiene do sono e rotinas noturnas.', 'sono', 'Sono', 'ebook', 'digital', false, '/logo-saude-bem.png', null, null, null, false, false, 'sono-reparador-ebook', null, array['habits']::text[], 'E-book Sono Reparador | Marketplace Saúde & Bem', 'Guia digital gratuito de higiene do sono e rotinas noturnas.', 'sono', '/logo-saude-bem.png', 'published');
insert into public.marketplace_products (id, slug, title, description, category, category_label, product_type, fulfillment, is_premium, image_url, current_price, old_price, installments, featured, editor_choice, library_slug, affiliate_slug, health_tags, seo_title, seo_description, seo_keywords, og_image_url, status) values ('e5000005-0005-4005-8005-000000000004', 'kit-emagrecimento-proprio', 'Kit Emagrecimento Saúde & Bem', 'Produto próprio: e-book + planilha de acompanhamento + checklist semanal.', 'emagrecimento', 'Emagrecimento', 'kit', 'own', false, '/logo-saude-bem.png', 47, 79, null, true, false, 'guia-emagrecimento-metabolico', null, array['bmi', 'protein', 'metabolism']::text[], 'Kit Emagrecimento Saúde & Bem | Marketplace Saúde & Bem', 'Produto próprio: e-book + planilha de acompanhamento + checklist semanal.', 'emagrecimento', '/logo-saude-bem.png', 'published');
insert into public.marketplace_products (id, slug, title, description, category, category_label, product_type, fulfillment, is_premium, image_url, current_price, old_price, installments, featured, editor_choice, library_slug, affiliate_slug, health_tags, seo_title, seo_description, seo_keywords, og_image_url, status) values ('e5000005-0005-4005-8005-000000000005', 'coracao-saudavel-proprio', 'Programa Coração Saudável', 'Produto próprio premium com e-book, protocolo e materiais de acompanhamento.', 'saude-cardiovascular', 'Saúde Cardiovascular', 'ebook', 'own', true, '/logo-saude-bem.png', 67, null, null, false, true, 'coracao-saudavel', null, array['cardiometabolic', 'habits']::text[], 'Programa Coração Saudável | Marketplace Saúde & Bem', 'Produto próprio premium com e-book, protocolo e materiais de acompanhamento.', 'saude-cardiovascular', '/logo-saude-bem.png', 'published');
insert into public.marketplace_products (id, slug, title, description, category, category_label, product_type, fulfillment, is_premium, image_url, current_price, old_price, installments, featured, editor_choice, library_slug, affiliate_slug, health_tags, seo_title, seo_description, seo_keywords, og_image_url, status) values ('e5000005-0005-4005-8005-000000000006', 'omega-3-cardiovascular', 'Ômega-3 Ultra Pure', 'Suplemento com EPA/DHA de alta pureza — apoio cardiometabólico.', 'saude-cardiovascular', 'Saúde Cardiovascular', 'suplemento', 'affiliate', false, '/logo-saude-bem.png', 89.9, null, null, false, false, null, 'omega-3-cardiovascular', array['cardiometabolic']::text[], 'Ômega-3 Ultra Pure | Marketplace Saúde & Bem', 'Suplemento com EPA/DHA de alta pureza — apoio cardiometabólico.', 'saude-cardiovascular', '/logo-saude-bem.png', 'published');
insert into public.marketplace_products (id, slug, title, description, category, category_label, product_type, fulfillment, is_premium, image_url, current_price, old_price, installments, featured, editor_choice, library_slug, affiliate_slug, health_tags, seo_title, seo_description, seo_keywords, og_image_url, status) values ('e5000005-0005-4005-8005-000000000007', 'monitor-sono-inteligente', 'Monitor de Sono Inteligente', 'Dispositivo wearable para acompanhar ciclos de sono e recuperação.', 'sono', 'Sono', 'dispositivo', 'affiliate', false, '/logo-saude-bem.png', 349, null, '10x sem juros', false, false, null, 'monitor-sono-inteligente', array['habits']::text[], 'Monitor de Sono Inteligente | Marketplace Saúde & Bem', 'Dispositivo wearable para acompanhar ciclos de sono e recuperação.', 'sono', '/logo-saude-bem.png', 'published');
insert into public.marketplace_products (id, slug, title, description, category, category_label, product_type, fulfillment, is_premium, image_url, current_price, old_price, installments, featured, editor_choice, library_slug, affiliate_slug, health_tags, seo_title, seo_description, seo_keywords, og_image_url, status) values ('e5000005-0005-4005-8005-000000000008', 'curso-metabolismo-ativo', 'Curso Metabolismo Ativo', 'Curso online sobre nutrição, treino e hábitos para composição corporal.', 'emagrecimento', 'Emagrecimento', 'curso', 'affiliate', false, '/logo-saude-bem.png', 197, null, null, true, false, null, 'curso-metabolismo-ativo', array['bmi', 'metabolism']::text[], 'Curso Metabolismo Ativo | Marketplace Saúde & Bem', 'Curso online sobre nutrição, treino e hábitos para composição corporal.', 'emagrecimento', '/logo-saude-bem.png', 'published');
insert into public.marketplace_products (id, slug, title, description, category, category_label, product_type, fulfillment, is_premium, image_url, current_price, old_price, installments, featured, editor_choice, library_slug, affiliate_slug, health_tags, seo_title, seo_description, seo_keywords, og_image_url, status) values ('e5000005-0005-4005-8005-000000000009', 'checklist-preventiva-digital', 'Checklist Saúde Preventiva', 'Material digital gratuito para acompanhamento preventivo anual.', 'longevidade', 'Longevidade', 'ebook', 'digital', false, '/logo-saude-bem.png', null, null, null, false, false, 'checklist-saude-preventiva', null, array['habits', 'cardiometabolic']::text[], 'Checklist Saúde Preventiva | Marketplace Saúde & Bem', 'Material digital gratuito para acompanhamento preventivo anual.', 'longevidade', '/logo-saude-bem.png', 'published');
insert into public.marketplace_products (id, slug, title, description, category, category_label, product_type, fulfillment, is_premium, image_url, current_price, old_price, installments, featured, editor_choice, library_slug, affiliate_slug, health_tags, seo_title, seo_description, seo_keywords, og_image_url, status) values ('e5000005-0005-4005-8005-000000000010', 'clube-saude-bem-premium', 'Clube Saúde & Bem Premium', 'Assinatura com biblioteca premium, protocolos avançados e área de membros.', 'longevidade', 'Assinatura', 'servico', 'subscription', true, '/logo-saude-bem.png', 29.9, null, null, false, false, null, null, array['habits', 'cardiometabolic', 'metabolism']::text[], 'Clube Saúde & Bem Premium | Marketplace Saúde & Bem', 'Assinatura com biblioteca premium, protocolos avançados e área de membros.', 'longevidade', '/logo-saude-bem.png', 'published');

select 'library_items' as table_name, count(*) as row_count from public.library_items
union all select 'marketplace_products', count(*) from public.marketplace_products;
