-- Fase 5.5 — Popular marketplace (10 ofertas iniciais)
-- Execute após 034_phase_5_4_marketplace.sql
-- Categorias: livros (2), sono (2), exercicios (2), equipamentos-saude/Saúde (2), bem-estar (2)
-- Destaques: 3 produtos (featured = true)

delete from public.affiliate_links
where id::text like 'f0550005-%';

insert into public.affiliate_links (
  id,
  title,
  slug,
  category,
  short_description,
  description,
  url,
  affiliate_url,
  image_url,
  product_type,
  brand,
  producer_name,
  affiliate_platform,
  benefits,
  target_audience,
  current_price,
  installments,
  featured,
  editor_choice,
  active,
  seo_title,
  seo_description,
  seo_keywords
) values
(
  'f0550005-0005-4005-8005-000000000001',
  'Hábitos Atômicos',
  'habitos-atomicos',
  'livros',
  'Guia prático para construir hábitos duradouros com micro-mudanças diárias.',
  'Best-seller de James Clear sobre como pequenas rotinas geram resultados consistentes em saúde, produtividade e bem-estar. Ideal para quem quer transformar comportamentos sem depender de motivação.',
  'https://example.com/affiliate/habitos-atomicos',
  'https://example.com/affiliate/habitos-atomicos',
  '/logo-saude-bem.png',
  'livro',
  'James Clear',
  'Alta Books',
  'amazon',
  E'Aprenda o método dos 1% de melhoria diária\nEstrutura clara para criar e manter hábitos\nAplicável a sono, alimentação e exercícios\nLinguagem acessível e baseada em ciência',
  'Quem deseja criar rotinas saudáveis de forma sustentável.',
  49.90,
  '',
  true,
  true,
  true,
  'Hábitos Atômicos | Recursos Saúde & Bem',
  'Livro prático para construir hábitos duradouros com micro-mudanças diárias.',
  'livros,habitos,rotina,bem-estar'
),
(
  'f0550005-0005-4005-8005-000000000002',
  'O Poder do Hábito',
  'o-poder-do-habito',
  'livros',
  'Entenda a ciência por trás dos hábitos e como reprogramar comportamentos.',
  'Obra clássica de Charles Duhigg que explica o loop do hábito (deixa, rotina, recompensa) e como aplicá-lo na vida real para melhorar saúde e qualidade de vida.',
  'https://example.com/affiliate/o-poder-do-habito',
  'https://example.com/affiliate/o-poder-do-habito',
  '/logo-saude-bem.png',
  'livro',
  'Charles Duhigg',
  'Objetiva',
  'amazon',
  E'Framework do loop do hábito\nExemplos reais de transformação\nAplicação em saúde e comportamento\nReferência em psicologia aplicada',
  'Leitores que querem entender o mecanismo dos hábitos antes de mudá-los.',
  44.90,
  '',
  false,
  false,
  true,
  'O Poder do Hábito | Recursos Saúde & Bem',
  'Ciência por trás dos hábitos e como reprogramar comportamentos.',
  'livros,habitos,comportamento'
),
(
  'f0550005-0005-4005-8005-000000000003',
  'Magnésio Glicinato para Sono',
  'magnesio-glicinato-sono',
  'sono',
  'Suplemento de magnésio glicinato para relaxamento noturno e qualidade do sono.',
  'Formulação de magnésio glicinato com alta biodisponibilidade, indicada para apoiar relaxamento muscular e transição para o sono. Complemento à higiene do sono, não substitui orientação médica.',
  'https://example.com/affiliate/magnesio-glicinato-sono',
  'https://example.com/affiliate/magnesio-glicinato-sono',
  '/logo-saude-bem.png',
  'suplemento',
  'Saúde & Bem',
  'Essential Nutrition',
  'hotmart',
  E'Magnésio glicinato de alta absorção\nApoio ao relaxamento noturno\nUso simples antes de dormir\nComplemento à rotina de sono',
  'Adultos com dificuldade leve de relaxamento noturno (consulte seu médico).',
  79.90,
  '3x de R$ 26,63',
  true,
  false,
  true,
  'Magnésio Glicinato para Sono | Saúde & Bem',
  'Suplemento para apoiar relaxamento noturno e qualidade do sono.',
  'sono,suplemento,magnesio'
),
(
  'f0550005-0005-4005-8005-000000000004',
  'Travesseiro Ergonômico Cervical',
  'travesseiro-ergonomico-cervical',
  'sono',
  'Travesseiro anatômico para alinhamento cervical e conforto durante a noite.',
  'Travesseiro ergonômico com suporte cervical, indicado para quem busca melhorar postura durante o sono e reduzir desconfortos matinais. Espuma de alta densidade com capa respirável.',
  'https://example.com/affiliate/travesseiro-ergonomico-cervical',
  'https://example.com/affiliate/travesseiro-ergonomico-cervical',
  '/logo-saude-bem.png',
  'dispositivo',
  'SleepWell',
  'SleepWell Brasil',
  'amazon',
  E'Suporte cervical anatômico\nEspuma de alta densidade\nCapa lavável e respirável\nMelhora conforto noturno',
  'Pessoas que acordam com rigidez cervical ou buscam mais conforto no sono.',
  189.00,
  '6x sem juros',
  false,
  false,
  true,
  'Travesseiro Ergonômico Cervical | Saúde & Bem',
  'Travesseiro anatômico para alinhamento cervical e conforto noturno.',
  'sono,travesseiro,ergonomia'
),
(
  'f0550005-0005-4005-8005-000000000005',
  'Kit Faixas de Resistência Pro',
  'kit-faixas-resistencia-pro',
  'exercicios',
  'Kit com 5 níveis de resistência para treino funcional em casa ou viagem.',
  'Conjunto de faixas elásticas com diferentes tensões, ideal para fortalecimento, mobilidade e reabilitação leve. Inclui bolsa de transporte e guia de exercícios básicos.',
  'https://example.com/affiliate/kit-faixas-resistencia-pro',
  'https://example.com/affiliate/kit-faixas-resistencia-pro',
  '/logo-saude-bem.png',
  'dispositivo',
  'MoveFit',
  'MoveFit',
  'amazon',
  E'5 níveis de resistência\nTreino funcional em qualquer lugar\nLeve e portátil\nGuia de exercícios incluso',
  'Iniciantes e intermediários que treinam em casa.',
  89.90,
  '',
  false,
  false,
  true,
  'Kit Faixas de Resistência Pro | Saúde & Bem',
  'Faixas elásticas para treino funcional em casa ou viagem.',
  'exercicios,treino,funcional'
),
(
  'f0550005-0005-4005-8005-000000000006',
  'Tapete de Yoga Antiderrapante',
  'tapete-yoga-antiderrapante',
  'exercicios',
  'Tapete extra grosso com grip superior para yoga, pilates e alongamento.',
  'Tapete de yoga 6mm com base antiderrapante, indicado para práticas diárias de mobilidade, alongamento e exercícios de baixo impacto. Material ecológico e fácil de limpar.',
  'https://example.com/affiliate/tapete-yoga-antiderrapante',
  'https://example.com/affiliate/tapete-yoga-antiderrapante',
  '/logo-saude-bem.png',
  'dispositivo',
  'ZenMat',
  'ZenMat',
  'amazon',
  E'Base antiderrapante estável\nEspessura confortável (6mm)\nIndicado para yoga e pilates\nMaterial resistente e durável',
  'Praticantes de yoga, pilates e alongamento em casa.',
  129.00,
  '4x de R$ 32,25',
  false,
  false,
  true,
  'Tapete de Yoga Antiderrapante | Saúde & Bem',
  'Tapete extra grosso para yoga, pilates e alongamento.',
  'exercicios,yoga,pilates'
),
(
  'f0550005-0005-4005-8005-000000000007',
  'Oxímetro de Pulso Digital',
  'oximetro-pulso-digital',
  'equipamentos-saude',
  'Monitor portátil de saturação e frequência cardíaca para uso doméstico.',
  'Oxímetro de dedo com display LED, leitura rápida de SpO2 e batimentos. Útil para monitoramento doméstico complementar — não substitui avaliação médica.',
  'https://example.com/affiliate/oximetro-pulso-digital',
  'https://example.com/affiliate/oximetro-pulso-digital',
  '/logo-saude-bem.png',
  'dispositivo',
  'HealthTrack',
  'HealthTrack',
  'amazon',
  E'Leitura de SpO2 e BPM\nDisplay claro e portátil\nUso doméstico complementar\nLigamento automático',
  'Adultos que desejam acompanhar saturação em casa (sob orientação profissional).',
  69.90,
  '',
  false,
  false,
  true,
  'Oxímetro de Pulso Digital | Saúde & Bem',
  'Monitor portátil de saturação e frequência cardíaca.',
  'saude,oximetro,monitoramento'
),
(
  'f0550005-0005-4005-8005-000000000008',
  'Balança Inteligente Bioimpedância',
  'balanca-inteligente-bioimpedancia',
  'equipamentos-saude',
  'Balança com análise de composição corporal via app Bluetooth.',
  'Balança inteligente com bioimpedância, sincronização via app para acompanhar peso, gordura corporal e hidratação. Ferramenta de autoconhecimento — não substitui avaliação clínica.',
  'https://example.com/affiliate/balanca-inteligente-bioimpedancia',
  'https://example.com/affiliate/balanca-inteligente-bioimpedancia',
  '/logo-saude-bem.png',
  'dispositivo',
  'FitScale',
  'FitScale',
  'amazon',
  E'Análise de composição corporal\nSincronização via app\nHistórico de evolução\nDesign slim e moderno',
  'Quem acompanha evolução de peso e composição corporal.',
  199.00,
  '5x sem juros',
  false,
  false,
  true,
  'Balança Inteligente Bioimpedância | Saúde & Bem',
  'Balança com análise de composição corporal via app.',
  'saude,balança,composicao-corporal'
),
(
  'f0550005-0005-4005-8005-000000000009',
  'Difusor Aromaterapia Ultrassônico',
  'difusor-aromaterapia-ultrassonico',
  'bem-estar',
  'Difusor ultrassônico silencioso para ambientes de relaxamento e meditação.',
  'Difusor de aromaterapia com nebulização ultrassônica, luz suave e timer automático. Ideal para criar ambiente de calma em quarto, sala ou espaço de meditação.',
  'https://example.com/affiliate/difusor-aromaterapia-ultrassonico',
  'https://example.com/affiliate/difusor-aromaterapia-ultrassonico',
  '/logo-saude-bem.png',
  'dispositivo',
  'CalmHome',
  'CalmHome',
  'amazon',
  E'Nebulização ultrassônica silenciosa\nTimer automático\nLuz ambiente suave\nAmbiente de relaxamento',
  'Quem pratica meditação, yoga ou busca ambientes mais calmos.',
  149.00,
  '',
  true,
  true,
  true,
  'Difusor Aromaterapia Ultrassônico | Saúde & Bem',
  'Difusor silencioso para relaxamento e meditação.',
  'bem-estar,aromaterapia,relaxamento'
),
(
  'f0550005-0005-4005-8005-000000000010',
  'Journal de Gratidão 90 Dias',
  'journal-gratidao-90-dias',
  'bem-estar',
  'Caderno guiado de gratidão e reflexão para 90 dias de prática diária.',
  'Journal estruturado com prompts diários de gratidão, reflexão e intenções. Ferramenta simples para cultivar bem-estar emocional e consistência na prática de mindfulness.',
  'https://example.com/affiliate/journal-gratidao-90-dias',
  'https://example.com/affiliate/journal-gratidao-90-dias',
  '/logo-saude-bem.png',
  'livro',
  'Mindful Press',
  'Mindful Press',
  'amazon',
  E'90 dias de prompts guiados\nPrática diária de gratidão\nFormato compacto\nApoio ao bem-estar emocional',
  'Quem busca uma prática simples de mindfulness e autoconhecimento.',
  39.90,
  '',
  false,
  false,
  true,
  'Journal de Gratidão 90 Dias | Saúde & Bem',
  'Caderno guiado de gratidão para 90 dias de prática.',
  'bem-estar,gratidao,mindfulness'
);

select
  count(*) filter (where active) as ativos,
  count(*) filter (where featured) as destaques
from public.affiliate_links
where id::text like 'f0550005-%';
